### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by fever324** [yishuiliunian/DZTableView#5]
https://github.com/yishuiliunian/DZTableView/blob/master/articles/Chapter1/subclassScrollView.md
开始提到的几个关键的临时变量**实在**reduceContentSize函数中初始化的

感谢博主写的这篇文章, 受益匪浅!

**Comment by fever324** [comment]
还有博主可以麻烦解释一下同一篇文章里height要加12吗?

      if (height < CGRectGetHeight(self.frame)) {
            height = CGRectGetHeight(self.frame) + 2;
       }
       height += 10;

感谢!

**Comment by yishuiliunian** [comment]
是为了让整个ContentSize大于当前的View的bounds.size
