### ISSUE TITLE
在 UIKit概述>>动画  这一节的内容是空的？

### ISSUE THREAD

**Issue by sh0rt2020** [yishuiliunian/DZTableView#7]
你好，最近在深入了解UIView这个东西，看到你的文章了，感觉写得挺不错的，但是`动画`这一节是本来就没有的内容吗？

**Comment by yishuiliunian** [comment]
动画这一节的内容没怎么深入去写，你可以看一下Core Animation的Guide。理解动画还是很有帮助的。

**Comment by sunwell** [comment]
好的，多谢回复~

**Comment by sunwell** [comment]
我在想，有没有可能针对大多数不太复杂的UITableView的使用场景来定制一个非常易用的TableView呢？不知道你有没有什么建议呢？

**Comment by yishuiliunian** [comment]
完全可以啊。精简版的TableView。

**Comment by sunwell** [comment]
哈哈，了解了~
